maevsi/vibetype

- nuxt/components/events/EventNew.vue
Not yet tested, but should work.
> feat: redirect to event on creation

- nuxt/nuxt.config.js
- nuxt/package.json
- nuxt/yarn.lock
setup robots.txt
Closes #68.
I also updated the config so that the nuxt.config.js urls point to http://localhost:3000 when running the dev script of the package.json.
> feat(robots): resolves #68

- nuxt/components/form/Form.vue
- nuxt/components/form/account/FormAccountSignIn.vue
> refactor(form): move assistance to form account sign in

- nuxt/server/api/auth.ts
- nuxt/server/api/tusd.ts
> feat(api): use public key for verification

- nuxt/components/form/contact/FormContact.vue
- nuxt/components/form/event/FormEvent.vue
- nuxt/plugins/util.ts
> fix(event): allow unchanged slug

- nuxt/components/ImageUploadGallery.vue
- nuxt/pages/account/_username/index.vue
- nuxt/pages/account/_username/settings/index.vue
- nuxt/pages/event/_username/_event_name/attendance/index.vue
- nuxt/pages/event/_username/_event_name/index.vue
- nuxt/pages/event/_username/_event_name/invitation/index.vue
- nuxt/pages/event/_username/_event_name/settings/index.vue
- nuxt/plugins/util.ts
> fix(validate): fetch network only

- nuxt/components/form/event/FormEvent.vue
> fix(form-event): set maximum datetime

- nuxt/assets/css/main.css
- nuxt/pages/account/_username/index.vue
- nuxt/pages/account/_username/settings/index.vue
- nuxt/pages/account/index.vue
- nuxt/pages/contact/index.vue
- nuxt/pages/dashboard/index.vue
- nuxt/pages/dev/index.vue
- nuxt/pages/event/_username/_event_name/attendance/index.vue
- nuxt/pages/event/_username/_event_name/index.vue
- nuxt/pages/event/_username/_event_name/invitation/index.vue
- nuxt/pages/event/_username/_event_name/settings/index.vue
- nuxt/pages/event/_username/index.vue
- nuxt/pages/event/index.vue
- nuxt/pages/eventGroup/_username/_event_group_name.vue
- nuxt/pages/eventGroup/_username/index.vue
- nuxt/pages/index.vue
- nuxt/pages/legal-notice.vue
- nuxt/pages/privacy-policy.vue
- nuxt/pages/task/account/email-address/verify.vue
- nuxt/pages/task/account/password/reset.vue
- nuxt/pages/task/event/create.vue
- nuxt/pages/task/event/unlock.vue
- nuxt/pages/upload/index.vue
- nuxt/pages/🫖/index.vue
> feat(pages): add transition

- Dockerfile
- nuxt/package.json
- nuxt/yarn.lock
And downgrade `isomorphic-dompurify` to make the webpage start again.
> ci(docker): add simple integration test

- nuxt/server/middleware/headers.ts
> fix(csp): temporarily disable trusted-types header

- nuxt/components/_/Error.vue
- nuxt/components/_/Header.vue
- nuxt/components/_/ImageUploadGallery.vue
- nuxt/components/_/TipTap.vue
- nuxt/components/account/AccountProfilePicture.vue
- nuxt/components/button/event/ButtonEventList.vue
- nuxt/components/contact/ContactListItem.vue
- nuxt/components/event/list/EventList.vue
- nuxt/components/form/account/FormAccountRegistration.vue
- nuxt/components/form/account/FormAccountSignIn.vue
- nuxt/components/form/account/password/FormAccountPasswordChange.vue
- nuxt/components/form/account/password/FormAccountPasswordReset.vue
- nuxt/components/form/account/password/FormAccountPasswordResetRequest.vue
- nuxt/components/form/event/FormEvent.vue
- nuxt/components/form/input/FormInput.vue
- nuxt/components/form/input/FormInputPhoneNumber.vue
- nuxt/components/form/input/FormInputUsername.vue
- nuxt/components/invitation/InvitationList.vue
- nuxt/pages/account/[username]/settings/index.vue
- nuxt/pages/dashboard/dev/index.vue
- nuxt/pages/dashboard/index.vue
- nuxt/pages/event/[username]/[event_name]/attendance/index.vue
- nuxt/pages/event/[username]/[event_name]/index.vue
- nuxt/pages/event/[username]/[event_name]/settings/index.vue
- nuxt/pages/index.vue
- nuxt/pages/task/account/email-address/verify.vue
- nuxt/pages/task/event/unlock.vue
- nuxt/pages/teapot/index.vue
The language data inside i18n tags has been reviewed. Changes  include:
- Correcting grammatical and spelling errors
- Consistent use of tenses
- Reducing the amount of abbreviations like "you'll" or "he's"
- Small stylistic tweaks to improve consistencies across languages
chore: resolve rebase conflict with vue3/all branch
fix: rename directories to avoid merge conflict
> feat: improve english translations

- .vscode/extensions.json
Uses vscode settings file to recommend extensions to users. This makes it easier to setup the repo for new users.
Included are extensions for syntax highlighting and code quality ensurance.
> chore: :wrench: add recommended extensions

- nuxt/components/_/Header.vue
- nuxt/components/_/ImageUploadGallery.vue
- nuxt/components/card/state/CardState.vue
- nuxt/components/contact/ContactListItem.vue
- nuxt/components/modal/Modal.vue
- nuxt/composables/useTusdFilesUrl.ts
- nuxt/pages/account/[username]/index.vue
- nuxt/pages/account/[username]/settings/index.vue
- nuxt/pages/dashboard/dev/index.vue
- nuxt/pages/dashboard/index.vue
- nuxt/pages/event/[username]/[event_name]/attendance/index.vue
- nuxt/pages/event/[username]/[event_name]/index.vue
- nuxt/pages/event/[username]/[event_name]/invitation/index.vue
- nuxt/pages/event/[username]/[event_name]/settings/index.vue
- nuxt/pages/task/account/sign-in.vue
- nuxt/pages/task/event/unlock.vue
- nuxt/pages/upload/index.vue
- nuxt/plugins/urql.ts
- nuxt/plugins/util/auth.ts
- nuxt/server/api/auth-key.ts
- nuxt/server/api/auth.ts
- nuxt/server/api/tusd.ts
Fixing stuff along the way... :walking:
> fix: common

- nuxt/components/layout/LayoutFooter.vue
- nuxt/cypress/e2e/robots.cy.ts
- nuxt/nuxt.config.ts
- nuxt/pnpm-lock.yaml
- nuxt/public/robots.txt
> fix(robots): upgrade to v3

- nuxt/nuxt.config.ts
- nuxt/package.json
- nuxt/pnpm-lock.yaml
> feat(nuxt): add pwa module

- nuxt/components/_/ImageUploadGallery.vue
> fix(imge-upload-gallery): correct button margin

- nuxt/components/form/FormDelete.vue
- nuxt/components/form/FormEvent.vue
- nuxt/components/form/account/password/FormAccountPasswordChange.vue
- nuxt/components/form/account/password/FormAccountPasswordReset.vue
- nuxt/components/invitation/InvitationList.vue
- nuxt/pages/event/[username]/[event_name]/index.vue
- nuxt/utils/util.ts
> feat(toast): do not await, display centered

- nuxt/components/_/ImageUploadGallery.vue
- nuxt/components/contact/ContactList.vue
- nuxt/components/form/FormEvent.vue
- nuxt/components/invitation/InvitationList.vue
- nuxt/components/modal/Modal.vue
- nuxt/pages/account/[username]/settings/index.vue
- nuxt/pages/event/[username]/[event_name]/attendance/index.vue
- nuxt/pages/event/[username]/[event_name]/index.vue
- nuxt/store/index.ts
- nuxt/types/modal.ts
Continuing changes to the modal that started in #1007.
See #915.
> refactor(modal): remove unused code

- nuxt/cypress/e2e/event.cy.ts
- nuxt/cypress/e2e/index.cy.ts
- nuxt/cypress/e2e/legalnotice.cy.ts
- nuxt/cypress/e2e/privacypolicy.cy.ts
- nuxt/cypress/e2e/taskAccountPasswordResetRequest.cy.ts
- nuxt/cypress/e2e/taskAccountRegister.cy.ts
- nuxt/cypress/e2e/taskAccountSignIn.cy.ts
- nuxt/cypress/e2e/taskEventUnlock.cy.ts
- nuxt/cypress/e2e/taskSearch.cy.ts
- nuxt/cypress/e2e/teapot.cy.ts
- nuxt/nuxt.config.ts
- nuxt/package.json
- nuxt/pages/index.vue
- nuxt/plugins/gtag.client.ts
- nuxt/pnpm-lock.yaml
I continued development on `@dargmuesli/nuxt-cookie-control`. It now does not reload the page whenever it wishes but let's us decide when to reload. We want to reload once "google-analytics" is either added or removed.
Upstream PR: https://github.com/dargmuesli/nuxt-cookie-control/pull/23
Resolves #1028.
> chore(deps): update @dargmuesli/nuxt-cookie-control to v3.0.0-beta.5

- nuxt/nuxt.config.ts
Well, it's green now :green_circle:
> feat(cookie-control): set checkbox active background color

- Dockerfile
- nuxt/pnpm-lock.yaml
- pnpm-lock.yaml
Resolves https://github.com/dargmuesli/jonas-thelemann/issues/178.
> chore(deps): upgrade

- nuxt/package.json
- nuxt/pnpm-lock.yaml
- nuxt/tailwind.config.ts
See https://tailwindcss.com/blog/tailwindcss-v3-3. We're especially using a typed configuration now! :partying_face:
> refactor(tailwind): migrate to v3.3

- pnpm-lock.yaml
> chore(deps): refresh lockfile

- nuxt/utils/validation.ts
> fix(validation): correct event existence variables

- nuxt/nuxt.config.ts
That's already covered by linting.
> fix(i18n): disable missing warning

- nuxt/components/form/input/FormInput.vue
- nuxt/components/form/input/FormInputUsername.vue
> fix(form-input-username): correct existence check

- nuxt/components/_/ImageUploadGallery.vue
- nuxt/components/form/account/FormAccountSignIn.vue
- nuxt/components/invitation/InvitationListItem.vue
- nuxt/pages/event/[username]/[event_name]/attendance/index.vue
- nuxt/pages/task/account/email-address/verify.vue
- nuxt/utils/util.ts
> refactor(promises): use await syntax

- nuxt/components/_/ImageUploadGallery.vue
> feat(uppy): display restriction error

- sqitch/deploy/table_contact.sql
- sqitch/deploy/table_event.sql
- sqitch/deploy/table_invitation.sql
- sqitch/deploy/table_profile_picture.sql
- sqitch/deploy/table_upload.sql
Preparation for https://github.com/maevsi/maevsi/issues/1209
Cases where cascading deletion do not make sense are removed and were added where they make sense.
> fix(sqitch): rework reference constraints

- nuxt/utils/constants.ts
> perf(cookie): shorten timezone name

- nuxt/utils/constants.ts
Preparation for a feature that allows to change the items per page to 10, 25, 50 or 100.
> feat(constants): set items per page to 10

- nuxt/app.vue
Doing a review on my own PR merged just a few minutes ago, I saw strings not translated yet. This PR adds internationalization for them.
> fix(app): add pwa i18n

- nuxt/package.json
- nuxt/server/api/auth-key.ts
- nuxt/server/api/tusd.ts
- nuxt/utils/util.ts
- pnpm-lock.yaml
> chore(deps): remove node-fetch

- README.md
Saw someone try to click on the images, now that's possible.
> docs(readme): add links to technology images

- nuxt/plugins/gtag.client.ts
Tighten cookie security for analytics cookies.
> chore(gtag): set cookie flags

- nuxt/components/form/input/FormInputIconWrapper.vue
- nuxt/pages/account/[username]/index.vue
- removes unneeded elements from form input icon wrapper
- corrects heading order
> fix: resolve html validation errors

- nuxt/components/_/DropDown.vue
- nuxt/components/modal/Modal.vue
- nuxt/layouts/default.vue
`inset` abbreviates `top, bottom, left, right`.
> chore(css): use inset

- .npmrc
Resolves https://github.com/maevsi/maevsi/pull/1271's build pipeline issue.
> fix(npm): correct configuration placement

- nuxt/server/api/auth-key.ts
Fixes the login. That's why there is the beta branch :smile: can't wait to have https://github.com/maevsi/maevsi/issues/909
See:
- https://github.com/unjs/ofetch/pull/239
> fix(ofetch): do not fetch raw

- nuxt/components/form/input/FormInputCaptcha.vue
- nuxt/plugins/urql.ts
- nuxt/server/api/auth-proxy.ts
- nuxt/store/index.ts
Not sure where that got lost, but the turnstile token seems to be never set.
> fix(turnstile): set store value

- nuxt/components/form/Form.vue
Fixes https://github.com/maevsi/maevsi/issues/900
> fix(form): correct error computation

- README.md
Update the README so that it properly explains the new sqitch setup.
> docs(readme): extract sqitch

- src/composables/useHeadLayout.ts
Just some SEO improvement. Adds `dir="ltr"` (or `rtl`) to `<html>`.
> feat(head): add `dir` attribute

- src/layouts/canvas.vue
- src/layouts/default.vue
- src/pages/account/[username]/index.vue
- src/pages/account/[username]/settings/index.vue
- src/pages/account/index.vue
- src/pages/contact/index.vue
- src/pages/dashboard/dev/index.vue
- src/pages/dashboard/index.vue
- src/pages/event/[username]/[event_name]/attendance/index.vue
- src/pages/event/[username]/[event_name]/index.vue
- src/pages/event/[username]/[event_name]/invitation/index.vue
- src/pages/event/[username]/[event_name]/settings/index.vue
- src/pages/event/[username]/index.vue
- src/pages/event/index.vue
- src/pages/index.vue
- src/pages/task/account/email-address/verify.vue
- src/pages/task/account/password/reset/index.vue
- src/pages/task/account/password/reset/request.vue
- src/pages/task/account/register.vue
- src/pages/task/account/sign-in.vue
- src/pages/task/event/create.vue
- src/pages/task/event/unlock.vue
- src/pages/task/search.vue
- src/pages/teapot/index.vue
- src/pages/upload/index.vue
The name setter is only required for components apparently.
> chore: remove layout and page names

- src/public/.well-known/security.txt
The links in security.txt are wrong. I corrected them.
> fix(well-known): fix security.txt link

- src/components/_/TipTap.vue
- src/components/form/FormContact.vue
- src/components/form/FormDelete.vue
- src/components/form/FormEvent.vue
- src/components/form/FormInvitation.vue
- src/components/form/account/FormAccountRegistration.vue
- src/components/form/account/FormAccountSignIn.vue
- src/components/form/account/password/FormAccountPasswordChange.vue
- src/components/form/account/password/FormAccountPasswordReset.vue
- src/components/form/account/password/FormAccountPasswordResetRequest.vue
- src/components/form/input/FormInputEmailAddress.vue
- src/components/form/input/FormInputPassword.vue
- src/components/form/input/FormInputUrl.vue
- src/components/form/input/FormInputUsername.vue
- src/locales/de.json
- src/locales/en.json
- src/pages/task/event/unlock.vue
- src/utils/constants.ts
- src/utils/validation.ts
See:
- https://github.com/maevsi/maevsi/issues/1015
> feat(form): remove lowercase validation for emails

- src/server/api/ical.post.ts
- src/tests/unit/ical.test.ts
Closes https://github.com/maevsi/stomper/issues/181
Resolves https://github.com/maevsi/stomper/issues/180
> fix(ical): correct hostname

- Dockerfile
- pnpm-lock.yaml
- src/package.json
Resolves https://github.com/maevsi/maevsi/issues/1418
> chore(deps): update

- .github/PULL_REQUEST_TEMPLATE.md
- src/plugins/sentry.client.ts
Fix https://github.com/maevsi/maevsi/issues/1447
I'm sorry the commit message is not up to your standards (commit hook failed) but I couldn't understand the reported error to make a better message.
> fix(sentry): reduce session replay sample rate

- src/components/contact/ContactList.vue
- src/components/form/FormContact.vue
- src/components/form/input/FormInputUsername.vue
Fixes https://github.com/maevsi/maevsi/issues/1456
> fix(form-contact): resolve username

- src/components/form/FormDelete.vue
- src/pages/accounts/[username]/settings/index.vue
- src/pages/events/[username]/[event_name]/settings/index.vue
- src/utils/util.ts
Resolves https://github.com/maevsi/maevsi/issues/980
> refactor(delete): use separate locale strings

- Dockerfile
The Dockerfile should not be depending on a certain architecture, so the pinned hash is removed.
> chore(docker): remove hashes

- src/components/layout/LayoutBreadcrumbs.vue
- src/pages/events/[username]/[event_name]/index.vue
- src/utils/constants.ts
> refactor(breadcrumbs): merge ui

- src/config/modules/index.ts
> refactor(sitemap): simplify exclusion

- src/app.vue
We not only check for old browsers anymore, but for browsers not supporting any of maevsi's features as well now.
> fix(i18n): correct browser support message

- pnpm-lock.yaml
- src/package.json
Update the i18n module to include a memory overflow fix.
> chore(deps): update @nuxtjs/i18n to v8.0.0-rc.9-28374728.64fa2f6

- src/utils/ui.ts
Corrects the index calculation for the hero images.
> fix(ui): correct hero image index

- src/config/modules/index.ts
- src/plugins/urql.ts
- tests/e2e/specs/server/robots.spec.ts-snapshots/robots-txt-content-chromium-linux.txt
- tests/e2e/specs/server/robots.spec.ts-snapshots/robots-txt-content-firefox-linux.txt
- tests/e2e/specs/server/robots.spec.ts-snapshots/robots-txt-content-webkit-linux.txt
Disallow session routes in the `robots.txt`.
> fix(robots): disallow session routes

- src/components/event/list/EventList.vue
- src/pages/account/edit/[username].vue
- src/pages/account/view/[username].vue
- src/pages/event/edit/[username]/[event_name].vue
- src/pages/event/view/[username]/[event_name]/attendance.vue
- src/pages/event/view/[username]/[event_name]/index.vue
- src/pages/event/view/[username]/[event_name]/invitation.vue
- src/utils/autoImport.ts
Increase snappyness of client side navigation.
> perf: add zalgo

- src/nuxt.config.ts
- src/tailwind.config.ts
`@nuxt/ui` took away the `gray`. And the plugin order.
cc @myyxl, @azolus
> fix(tailwind): correct style priorities

- src/server/api/auth-proxy.ts
Make https://postgraphile.maev.si/graphiql accessible again.
> fix(auth-proxy): drop non-post requests

- .gitignore
- .idea/inspectionProfiles/Project_Default.xml
- .idea/maevsi.iml
- .idea/modules.xml
- .idea/prettier.xml
- .idea/vcs.xml
> chore(ide): add webstorm ide configuration

- src/.config/nuxt.ts
- src/app.vue
- src/components/form/account/FormAccountSignIn.vue
- src/pages/session/create.vue
- src/stores/maevsi.ts
Allow to provide a link to account deletion.
> feat(session): allow to redirect to account deletion

- pnpm-lock.yaml
- tests/.lintstagedrc
- tests/eslint.config.js
- tests/package.json
> chore(lint): remove plugin yml

- src/components/layout/menu/LayoutMenuItem.vue
- src/eslint.config.js
- tests/eslint.config.js
Use `AppLink` wherever possible.
> refactor(layout-menu-item): use app link

- src/components/layout/LayoutHeader.vue
- src/components/layout/menu/LayoutMenuSidebar.vue
- src/plugins/sentry.client.ts
- src/plugins/urql.ts
- src/stores/maevsi.ts
> chore: various

- src/components/button/ButtonApp.vue
- src/composables/platform.ts
- src/pages/index.vue
- src/server/middleware/headers.ts
- src/server/middleware/platform.ts
- src/server/types/platform.d.ts
Hide content which is not meant to be displayed in apps.
> feat(app): detect

- src/components/form/input/FormInputPassword.vue
The exemplary password now looks as if it was an example :joy:
> fix(form-input-password): clarify placeholder

- pnpm-lock.yaml
- src/package.json
- src/plugins/sentry.client.ts
> chore(deps): remove vue-tsc

- src/.config/nuxt.ts
- src/pages/dashboard/index.vue
- src/pages/session/edit/[id]/index.vue
> feat: content

- pnpm-lock.yaml
- src/gql/documents/fragments/achievementItem.ts
- src/gql/documents/mutations/achievement/achievementUnlock.ts
- src/gql/documents/queries/achievement/achievementsAll.ts
- src/gql/generated/fragment-masking.ts
- src/gql/generated/gql.ts
- src/gql/generated/graphcache.ts
- src/gql/generated/graphql.ts
- src/gql/generated/introspection.ts
- src/package.json
- src/pages/account/view/[username].vue
- src/pages/index.vue
- src/plugins/urql.ts
- src/server/api/auth-key.ts
- src/server/api/auth-proxy.ts
- src/server/api/auth.ts
- src/server/api/ical.post.ts
- src/server/api/tusd.post.ts
- src/server/api/upload.delete.ts
- src/server/utils/auth.ts
- src/utils/validation.ts
- tests/e2e/specs/server/ical.spec.ts
Add the first proper achievement.
> feat(achievements): meet the team

- src/pages/account/view/[username].vue
- src/pages/index.vue
- tests/e2e/specs/server/sitemap.spec.ts
Adds empty state text for when no achievements are unlocked yet.
> fix(achievement): add empty state text

- README.md
Addresses improvement suggestions to the setup flow voiced in https://github.com/maevsi/maevsi/issues/1630.
> docs(readme): improve setup

- src/eslint.config.js
Some typechecking for JavaScript files.
> chore(typescript): check eslint configuration

- src/.config/nuxt.ts
- src/config/environments/development.ts
- src/server/utils/constants.ts
- src/utils/constants.ts
Things I came across along the way.
> feat(dev): any

- src/components/button/Button.vue
- src/components/contact/ContactPreview.vue
- src/components/form/FormCheckbox.vue
- src/components/form/FormEvent.vue
- src/components/form/FormInvitation.vue
- src/components/layout/footer/LayoutFooter.vue
- src/composables/dateTime.ts
- src/pages/account/view/[username].vue
- src/pages/event/view/[username]/[event_name]/index.vue
- src/pages/event/view/[username]/index.vue
- src/utils/autoImport.ts
The event creation page did not hydrate properly.
> fix(timezone): correct hydration error

- src/server/api/auth-proxy.ts
Resolves https://github.com/maevsi/maevsi/issues/1567
> fix(proxy): don't verify captcha for anonymous authentication

- src/config/modules/security.ts
Allow to disable the rate limiter dynamically until performance issues are resolved, like:
- https://github.com/maevsi/maevsi/issues/1654
> feat(security): add rate limiter flag

- src/.config/nuxt.ts
- src/config/modules/security.ts
- src/server/api/auth-proxy.ts
- src/server/plugins/security.ts
Use route rules and runtime configuration this time.
> fix(security): correct rate limiter disabling at runtime

- src/components/invitation/InvitationList.vue
- src/gql/documents/queries/invitation/invitationsAll.ts
- src/gql/generated/fragment-masking.ts
- src/gql/generated/gql.ts
- src/gql/generated/graphcache.ts
- src/gql/generated/graphql.ts
- src/plugins/urql.ts
- src/server/api/auth-proxy.ts
Some manual optimization for list loading after new items are available.
> fix(invitation): reset query on list change

- src/components/contact/ContactList.vue
Fix for invitation list, now for contacts.
> fix(cache): reset contact query on contact addition

- src/.config/nuxt.ts
- src/server/api/ical.post.ts
- src/server/utils/ical.ts
Correct schema definition and disable xss validator for ical endpoint.
> fix(schema): correct for ical

- src/pages/invitation/unlock.vue
These paths are required as of now.
> fix(invitation): add paths to redirect

- src/app.vue
Currently, the styling is not available during server side rendering.
> fix(render): show cookie banner on client side only

- .renovaterc.json
- package.json
- pnpm-lock.yaml
- src/package.json
Works around https://github.com/nuxt-modules/turnstile/issues/342
> fix(deps): pin `@nuxtjs/turnstile` to v0.9.6

- src/server/utils/ical.ts
- tests/unit/ical.test.ts
The event link should be up to date.
> fix(ical): correct event link

- src/components/form/input/FormInput.vue
- src/pages/dashboard/index.vue
- src/utils/validation.ts
- the validation icon should display within the parent component.
also:
- mark invitations as under construction
- mark api validations as to be debounced
> fix(form-input): correct icon placement

- .renovaterc.json
- package.json
- pnpm-lock.yaml
The most recent version contains the necessary fix now.
> chore(deps): unpin `caniuse-lite`

- .dockerignore
- Dockerfile
It's always nice not to run as root. Should also help with AWS credential reading.
> fix(docker): run as user `node` in production

- src/gql/generated/graphcache.ts
- src/gql/generated/graphql.ts
- src/gql/generated/introspection.ts
Update the API type definitions.
cc @huzaifaedhi22
> chore(gql): regenerate

- src/.config/nuxt.ts
- src/app/composables/host.ts
- src/app/composables/networking.ts
- src/app/composables/tusd.ts
- src/server/assets/emails/components/MaevsiLogo.vue
- src/server/plugins/event-stream.ts
- src/server/plugins/security.ts
- src/server/utils/networking.ts
- src/server/utils/notification.ts
- src/server/utils/tusd.ts
- src/server/utils/vio.ts
- src/shared/utils/tusd.ts
> fix(email): correct link domain

- src/app/composables/tusd.ts
- src/server/assets/emails/components/MaevsiLogo.vue
- src/server/plugins/event-stream.ts
- src/server/plugins/security.ts
- src/server/utils/tusd.ts
- src/server/utils/vio.ts
- src/shared/utils/tusd.ts
Necessary as the request is not available in nitro plugins.
> fix(networking): get host from site url instead of request

- src/app/app.vue
- src/app/components/form/FormEvent.vue
- src/app/composables/dateTime.ts
- src/app/composables/timezone.ts
It appears there is an issue with composable usage server-side. This PR tries to fix it.
> fix(timezone): use as composable on client side

- src/app/components/invitation/InvitationList.vue
- src/app/pages/event/view/[username]/[event_name]/guest.vue
- src/app/pages/event/view/[username]/[event_name]/index.vue
- src/app/pages/event/view/[username]/[event_name]/invitation.vue
- src/app/utils/validation.ts
An alias is added that allows access to the page with the `/guest` suffix in addition to the currently existing `/invitation` suffix.
TODO:
> feat(event): rename invitation page to guest page

- .renovaterc.json
- package.json
- pnpm-lock.yaml
Vue language tools are now compatible with newer versions of typescript.
> chore(deps): unpin typescript

- tests/e2e/utils/constants.ts
Reenable a previously disabled check that currently works.
> test(page): check cookie control for readiness

- Dockerfile
There is a current bug in Node's corepack for which this PR adds a workaround until the upstream issue is resolved:
- https://github.com/nodejs/corepack/issues/612
> ci(corepack): workaround key issue

- Dockerfile
Second hotfix, following #1743 🥵
> ci(corepack): update

- .github/workflows/browserslist-regex.yml
- .github/workflows/ci.yml
- .github/workflows/release-schedule.yml
Includes CI workarounds as known from #1747
> chore(deps): update dargmuesli/github-actions to v2.3.15

- src/.config/nuxt.ts
- src/config/environments/development.ts
- src/sentry.server.config.ts
- src/server/api/notification.post.ts
- src/server/utils/dependencies/firebase.ts
The legacy syntax resolves to CJS, the modern to ESM. We require the modern syntax.
> fix(firebase): use modern syntax

- src/app/pages/session/view/[id].vue
- src/app/plugins/firebase.client.ts
- src/app/service-worker/sw.ts
- src/app/utils/dependencies/firebase.ts
Show FCM Token instead of copying it
> feat(token): show token using dialog

- .renovaterc.json
- package.json
- pnpm-lock.yaml
The `require` bug was fixed:
- https://github.com/nodejs/require-in-the-middle/pull/106
> chore(deps): unpin require-in-the-middle

- pnpm-lock.yaml
- src/package.json
This dependency is not in use.
> chore(deps): remove `nuxt-seo-ui`

- package.json
- tests/package.json
> refactor(package): sort

- package.json
Resolves a new warning with pnpm v10.
> chore(package): ignore build dependencies

- src/app/assets/css/tailwind.css
Should reenable the user to pick a dark mode.
> fix(style): readd dark mode override

- src/app/pages/session/view/[id].vue
- src/app/plugins/firebase.client.ts
- src/app/plugins/ios.client.ts
- src/app/plugins/notification.client.ts
- src/app/stores/notification.ts
- src/app/types/modules/webkit.d.ts
- src/app/utils/index.ts
- src/app/utils/pwa/index.ts
- src/app/utils/pwa/ios.ts
Added the iOS implementation for notifications
> feat(notification): add ios implementation

- tests/package.json
Draft because I want to test the CI still.
> test(e2e): use https for development server

- .renovaterc.json
- package.json
- pnpm-lock.yaml
- src/package.json
The linting issue in the library was fixed.
> chore(deps): unpin `vue-tsc`

- src/server/api/ical.post.ts
- src/server/utils/ical.ts
- tests/unit/ical.test.ts
The event visibility can be set for calendar invitations.
> feat(ical): set class

- package.json
- src/gql/generated/graphcache.ts
- src/gql/generated/graphql.ts
- src/gql/generated/introspection.ts
Just an update for the GraphQL schema.
> chore(gql): update schema

- .commitlintrc.js
- .github/PULL_REQUEST_TEMPLATE.md
- .husky/commit-msg
- package.json
- pnpm-lock.yaml
After reverting back from squash merging, all commit messages must now match the convention again.
cc @huzaifaedhi22
> chore(github): readd commit name format requirement

- src/app/components/form/FormDelete.vue
- src/app/components/form/FormEvent.vue
- src/app/components/form/account/password/FormAccountPasswordChange.vue
- src/app/components/form/account/password/FormAccountPasswordReset.vue
- src/app/components/guest/GuestListItem.vue
- src/app/composables/alert.ts
- src/app/pages/event/view/[username]/[event_name]/index.vue
- src/app/utils/notification.ts
This removes about 20KB from the bundle's entrypoint JS file.
> perf(bundle): extract sweetalert from client entrypoint

- src/app/utils/validation.ts
Simple cleanup, `throwError` is indeed more flexible in this case as it can be used outside of route middlewares.
> chore(validation): remove comments

- pnpm-lock.yaml
- src/app/error.vue
See https://github.com/nuxt-modules/og-image/pull/330
> fix(seo): define open graph image for error pages

- CONTRIBUTING.md
Some extensions to the documentation that came up in collaboration.
> docs(contributing): extend

- src/app/assets/css/maevsi.css
- src/app/components/card/CardButton.vue
- src/app/components/event/EventHeroImage.vue
- src/app/components/event/list/EventListItem.vue
- src/app/components/typography/TypographyH6.vue
- src/app/components/typography/TypographySubtitleSmall.vue
Updates the event card style, mainly fixing the title selection ring and removing some content not needed in the new design.
> feat(card): restyle for event

- src/app/components/event/EventSearch.vue
- src/app/pages/event/view/[username]/index.vue
Following https://github.com/maevsi/maevsi/pull/1800, the user-specific event page shows no events anymore. This readds the event list for that page and also fixes the display of the load more button.
> fix(event): load events per user

- src/app/components/tailwind/TailwindDiscord.vue
Removes a duplicate class and adds a missing translation parameter.
> fix(component): correct tailwind discord internationalization and style

- CONTRIBUTING.md
- src/app/components/_/DropDown.vue
- src/app/components/_/ScrollContainer.vue
- src/app/components/contact/ContactList.vue
- src/app/components/form/Form.vue
- src/app/components/form/FormContact.vue
- src/app/components/form/FormDelete.vue
- src/app/components/form/FormGuest.vue
- src/app/components/form/account/FormAccountRegistration.vue
- src/app/components/form/account/FormAccountSignIn.vue
- src/app/components/form/account/password/FormAccountPasswordChange.vue
- src/app/components/form/account/password/FormAccountPasswordReset.vue
- src/app/components/form/account/password/FormAccountPasswordResetRequest.vue
- src/app/components/form/input/FormInputCaptcha.vue
- src/app/components/guest/GuestList.vue
- src/app/components/guest/GuestListItem.vue
- src/app/components/upload/UploadGallery.vue
- src/app/layouts/canvas.vue
- src/app/pages/account/edit/[username].vue
- src/app/pages/account/verify.vue
- src/app/pages/account/view/[username].vue
- src/app/pages/event/edit/[username]/[event_name].vue
- src/app/pages/event/ingest/image.vue
- src/app/pages/event/view/[username]/[event_name]/attendance.vue
- src/app/pages/event/view/[username]/index.vue
- src/app/pages/guest/unlock.vue
- src/app/pages/index.vue
Let's use Vue 3.5's modern [template refs](https://vuejs.org/guide/essentials/template-refs).
> refactor(vue): use template refs

- src/server/api/auth-proxy.ts
- src/server/api/tusd.post.ts
- src/server/api/upload.delete.ts
- src/server/plugins/event-stream.ts
- src/server/plugins/openai.ts
- src/server/utils/constants.ts
- src/server/utils/dependencies/firebase.ts
- src/server/utils/email.ts
- src/server/utils/notification.ts
- src/shared/utils/auth.ts
Logging using `consola` looks a bit better in the server logs. Also third party secrets are now checked separately.
> chore(server): improve secret logging

- src/app/app.vue
- src/app/error.vue
- src/i18n/locales/de.json
- src/i18n/locales/en.json
Clean up the site configuration a bit.
> refactor(head): shorten site configuration

- Dockerfile
> chore(docker): remove corepack workaround

- package.json
- src/config/modules/i18n.ts
Resolves a pnpm warning for a built dependency and one by nuxt-i18n about a deprecation.
> chore: resolve warnings

- src/app/pages/account/edit/[username].vue
- src/app/pages/account/view/[username].vue
- src/app/pages/event/edit/[username]/[event_name].vue
- src/app/pages/event/view/[username]/[event_name]/attendance.vue
- src/app/pages/event/view/[username]/[event_name]/guest.vue
- src/app/pages/event/view/[username]/[event_name]/index.vue
- src/app/pages/event/view/[username]/index.vue
- src/app/utils/validation.ts
We can inline our page validations to gain some performance while removing detection of `403` errors for now.
> perf(validation): inline existence checks

- src/content/de/legal-notice.md
- src/content/de/privacy-policy.md
Thank for the feedback @sthelemann!
> fix(legal): correct typos

- src/app/components/_/Benefit.vue
- src/app/components/_/Steps.vue
- src/app/components/card/CardButton.vue
- src/app/components/contact/ContactPreview.vue
- src/app/components/form/radio-button/FormRadioButtonTailwind.vue
- src/app/components/layout/LayoutFeed.vue
- src/app/components/layout/LayoutHeader.vue
- src/app/components/layout/footer/LayoutFooter.vue
- src/app/components/layout/menu/LayoutMenuItemList.vue
- src/app/components/modal/Modal.vue
- src/app/components/notification/NotificationFriendRequest.vue
- src/app/components/notification/NotificationIndicator.vue
- src/app/components/search/SearchBar.vue
- src/app/components/upload/UploadGallery.vue
- src/app/pages/account/edit/[username].vue
- src/app/pages/account/view/[username].vue
- src/app/pages/event/ingest/image.vue
- src/app/pages/session/edit/[id]/index.vue
A shorthand for width and height.
> refactor(tailwind): use `size` utility

- src/server/utils/constants.ts
Allows for hot reload of our markdown content.
> chore(content): allow websocket connection in development

- src/app/composables/testing.ts
- src/app/pages/account/verify.vue
- src/app/plugins/urql.ts
- src/server/api/test/graphql.post.ts
- src/server/utils/testing.ts
- tests/e2e/specs/server/headers.spec.ts
- tests/e2e/specs/server/robots.spec.ts
- tests/e2e/specs/server/sitemap.spec.ts
- tests/e2e/utils/tests.ts
Resolves https://github.com/maevsi/vibetype/issues/1674
cc @huzaifaedhi22
> test(e2e): mock graphql api

- src/app/components/layout/menu/LayoutMenuBottomNavigation.vue
> fix(components): wrap bottom navigation in landmark

- src/server/middleware/platform.ts
First step to unified platform keys. When the apps are updated, the old variants can be removed.
> feat(platform): allow for header and cookie key unification

- src/app/components/_/AppError.vue
Deduplicate app name hardcoding.
> refactor(components): use variable app name

- src/app/pages/docs/legal/conduct/index.vue
- src/content/de/conduct.md
- src/content/en/conduct.md
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-Mobile-Chrome-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-Mobile-Safari-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-chromium-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-Mobile-Chrome-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-Mobile-Safari-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-chromium-linux.xml
Will be linked to in the terms of use.
> feat(pages): add code of conduct

- src/app/pages/docs/legal/attributions/index.vue
Improves the template for legal attributions.
> fix(pages): correct attributions title

- src/content/de/imprint.md
- src/content/de/privacy.md
- src/content/de/terms.md
- src/content/en/terms.md
Just to track changes in git, will be sourced from the backend.
> feat(content): add terms of use

- pnpm-lock.yaml
- src/package.json
> fix(deps): update @dargmuesli/nuxt-cookie-control to v9.0.1

- src/server/utils/constants.ts
The connection will be made to localhost, not our production address.
> fix(content): correct websocket hostname

- src/app/assets/css/app.css
- src/app/components/form/input/FormInput.vue
- src/app/components/form/input/FormInputCaptcha.vue
- src/app/components/form/input/FormInputUsername.vue
- src/i18n/locales/de.json
- src/i18n/locales/en.json
Improves focus rings, the username input and form input helpers.
> fix(style): minor touchups

- src/app/pages/account/create/index.vue
- src/content/de/privacy-consent.md
- src/content/en/privacy-consent.md
Adds the consent text in addition to the general privacy policy.
> feat(content): add privacy consent

- src/app/pages/account/password/reset/request.vue
We got a design update, and a duplicate string is removed.
> fix(account): remove button for email confirmation

- src/app/components/form/account/FormAccountRegistration.vue
Design team agreed to show this at registration too, not only in password reset flow.
> feat(account): indicate password strength at registation

- src/content/de/conduct.md
- src/content/en/conduct.md
Extended rewrite of the initial version.
> feat(content): update code of conduct

- src/app/assets/css/app.css
- src/app/components/account/legal/AccountLegalConsent.vue
- src/app/components/form/account/FormAccountRegistration.vue
- src/app/pages/account/create/index.vue
- src/content/de/privacy-consent.md
- src/content/de/terms.md
- src/content/en/privacy-consent.md
- src/content/en/terms.md
Some tweaks to the registration flow, especially fixing the overflowing table in the privacy consent document.
> feat(account): tweak registration

- src/app/pages/event/view/[username]/[event_name]/index.vue
> fix(guest): correct preview navigation

- src/.config/nuxt.ts
Upstream fix was released, so now we should be able to remove the workaround.
> chore(content): remove prerender ignore

- src/server/utils/dependencies/postgres.ts
The site name can't be used in this case.
> fix(server): correct postgres query variables

- src/app/components/account/legal/AccountLegalConsent.vue
- src/app/components/app/AppHr.vue
- src/app/components/app/AppTipTap.vue
- src/app/components/app/button/AppButton.vue
- src/app/components/button/ButtonIcon.vue
- src/app/components/button/ButtonIconBackRoute.vue
- src/app/components/form/input/FormInput.vue
- src/app/components/form/input/FormInputSearch.vue
- src/app/components/layout/LayoutHeader.vue
- src/app/components/layout/LayoutPage.vue
- src/app/components/layout/LayoutTopBar.vue
- src/app/components/tailwind/TailwindFeature.vue
- src/app/pages/early-bird/create.vue
- src/app/pages/flow/welcome/index.vue
Extract a shared button and some minor fixes.
> feat(components): extract icon back button for route navigation

- src/app/components/form/FormSupportContact.vue
- src/app/pages/session/edit/[id]/index.vue
- src/app/pages/support/contact/index.vue
- src/server/api/monday/contact.post.ts
- src/server/plugins/monday.ts
- src/server/utils/dependencies/monday.ts
- src/shared/utils/schema.ts
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-Mobile-Chrome-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-Mobile-Safari-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-chromium-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-Mobile-Chrome-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-Mobile-Safari-linux.xml
- tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-chromium-linux.xml
Extends the Monday integration with a contact form page.
> feat(pages): add contact form

- pnpm-lock.yaml
- src/config/modules/i18n.ts
- src/package.json
Includes a fix for file paths in the build output.
> chore(deps): upgrade @nuxtjs/i18n to v10.0.0-beta.3

- src/app/components/form/account/FormAccountRegistration.vue
- src/app/components/form/account/FormAccountSignIn.vue
An error showed on success which is not really helpful.
> fix(components): correct authentication form success computation

- src/server/utils/dependencies/postgres.ts
Schema must be given for production, but can't be set using a variable.
> fix(server): correct postgres schema

- src/content/de/privacy.md
- src/content/en/privacy.md
> feat(content): update backup service in privacy policy

- src/app/pages/session/view/[id].vue
Forgotten to add in 1b27b18f126e9a59d5fb7bca752d65ac51705819.
> fix(pages): disallow robots for session view

- src/app/pages/session/edit/[id]/color-scheme.vue
- src/app/pages/session/edit/[id]/language.vue
Apparently all sub pages need to have this route rule too for it to apply correctly.
> fix(pages): fully disable robots for session edit

- src/app/components/scn/button/Button.vue
- src/app/components/scn/button/index.ts
- src/app/components/scn/calendar/Calendar.vue
- src/app/components/scn/calendar/CalendarCell.vue
- src/app/components/scn/calendar/CalendarCellTrigger.vue
- src/app/components/scn/calendar/CalendarGrid.vue
- src/app/components/scn/calendar/CalendarGridBody.vue
- src/app/components/scn/calendar/CalendarGridHead.vue
- src/app/components/scn/calendar/CalendarGridRow.vue
- src/app/components/scn/calendar/CalendarHeadCell.vue
- src/app/components/scn/calendar/CalendarHeader.vue
- src/app/components/scn/calendar/CalendarHeading.vue
- src/app/components/scn/calendar/CalendarNextButton.vue
- src/app/components/scn/calendar/CalendarPrevButton.vue
Update the nuxt-shadcn calendar component.
> chore(components): update calendar

- src/app/components/typography/TypographyH3.vue
- src/app/components/typography/TypographyH4.vue
- src/app/components/typography/TypographyH6.vue
Makes headings look a lil nicer, see https://tailwindcss.com/docs/text-wrap.
> feat(components): wrap headings balanced

- src/app/assets/css/app.css
- src/app/components/contact/ContactList.vue
- src/app/components/contact/ContactListItem.vue
- src/app/components/guest/GuestList.vue
- src/app/components/guest/GuestListItem.vue
- src/app/components/layout/LayoutTable.vue
- src/app/components/layout/LayoutTd.vue
- src/app/components/layout/LayoutTh.vue
Some components will use table elements that should not inherit a global style.
> refactor(components): convert from table base styles

- src/.config/nuxt.ts
- src/app/pages/session/create/index.vue
- src/shared/utils/schema.ts
Some naming adjustments, extend vite's optimized dependencies.
> refactor: align variable names

- src/app/pages/account/verify/index.vue
- src/app/pages/early-bird/create.vue
Allow back navigation on page that redirects to login. Currently you can't move back because you're redirected back right away.
> fix(pages): replace history on redirection to login

- src/app/pages/session/edit/index.vue
Users not logged in will be asked to login or create an account when they try to access ai or early bird setup.
> feat(session): show customization features to anyone

- src/server/utils/constants.ts
Resolves a content security policy error related to nuxt content's hot reloading until the fix upstream is merged and released: https://github.com/nuxt/content/pull/3344
> fix(security): add workaround for upstream nuxt content issue

- src/app/assets/css/vibetype.css
- src/app/components/form/input/FormInputSearch.vue
- src/app/components/layout/menu/LayoutMenuItem.vue
- src/app/components/tailwind/TailwindFeature.vue
- src/app/components/tailwind/TailwindPricing.vue
Coordinated a naming simplification with the design team.
> refactor(style): simplify accent naming

- .renovaterc.json
- package.json
- pnpm-lock.yaml
- src/config/modules/i18n.ts
- src/package.json
There seems to be an issue starting with @nuxtjs/i18n v10.0.0-beta.3 and @sentry/nuxt.
Waiting for:
- https://github.com/nuxt-modules/i18n/issues/3595
> chore(deps): unpin @nuxtjs/i18n

- src/.codegenrc.ts
- src/eslint.config.js
- src/gql/generated/graphcache.ts
Working towards proper types in generated GraphQL files.
> chore(gql): extend linting

- src/app/components/app/AppMap.vue
- src/app/components/layout/menu/LayoutMenuBottomNavigation.vue
- src/app/components/preference/step/PreferenceStepLocation.vue
- src/app/plugins/urql.ts
- src/gql/documents/fragments/preferenceEventLocationItem.ts
- src/gql/documents/mutations/preference/preferenceEventLocationCreate.ts
- src/gql/documents/mutations/preference/preferenceEventLocationDeleteById.ts
- src/gql/documents/queries/preference/preferenceEventLocationsAll.ts
- src/gql/generated/gql.ts
- src/gql/generated/graphcache.ts
- src/gql/generated/graphql.ts
- src/gql/generated/introspection.ts
Switch from account location to the newly added location preference.
See:
- https://github.com/maevsi/sqitch/pull/214
> feat(components): add location preference

- src/app/components/icon/logo/IconLogo.vue
- src/app/components/icon/logo/IconLogoWithText.vue
This PR fixes
- Typo in viewBox , causing distortion in logo after navigation.
> fix(components): correct view box casing

- pnpm-lock.yaml
- src/package.json
`dompurify` includes its own types now.
> chore(deps): remove `@types/dompurify`

- package.json
- pnpm-lock.yaml
Testing if that version is the only current dependency issue.
> chore(deps): pin nuxt-og-image to v5.1.7

- src/content/de/conduct.md
- src/content/en/conduct.md
> feat(content): link contact form

- src/server/utils/dependencies/monday.ts
> fix(utils): correct monday key

- pnpm-lock.yaml
> chore(deps): update lockfile

- src/app/components/event/report/EventReportDrawer.vue
- src/app/pages/event/view/[username]/[event_name]/index.vue
This PR
- fixes event report drawer not opening
> fix(event): report drawer not opening

- src/app/components/account/AccountSearch.vue
The new pagination / endless scroll is now compatible with searching the same list.
> fix(account): clear `after` on search

- pnpm-lock.yaml
- src/package.json
Resolves https://github.com/maevsi/vibetype/issues/2019
> chore(deps): update isomorphic-dompurify to v2.26.0

- src/server/plugins/security.ts
Let's not infer types in this case but use their actual definition.
> refactor(types): import from nuxt-security

- package.json
- pnpm-lock.yaml
- src/package.json
No need to set these versions anymore. I made some fixes upstream.
> chore(deps): drop @intlify pins

- src/app/composables/head.ts
- src/app/pages/docs/legal/imprint/index.vue
- src/app/pages/docs/legal/privacy/index.vue
- src/server/types/h3.ts
- chore(docs): amend external links to legal pages
- refactor(types): sort h3 event context declaration
- refactor(seo): correct usage of deprecated head functions
> chore: housekeeping

- src/app/components/layout/menu/LayoutMenuItemList.vue
Reactive a previous implementation that showed the user's profile picture in the "Account" menu item.
> feat(account): show profile picture in menu

- src/app/components/app/AppTipTap.vue
Resolves https://github.com/maevsi/vibetype/issues/1419
> feat(tiptap): support justified alignment

- src/gql/generated/graphcache.ts
- src/gql/generated/graphql.ts
- src/gql/generated/introspection.ts
Update the graphql schema to the most recent sqitch version.
> chore(gql): update

- src/app/components/event/card/EventCard.vue
The badge is shown on all event cards rn, which is incorrect and fixed in this PR.
> fix(event): show match only on recommendation

- src/config/modules/pwa.ts
The URL protocol and type is be added for scope extensions.
> fix(modules): correct pwa scope extensions

- src/app/composables/head.ts
- src/app/pages/event/edit/[username]/[event_name].vue
- src/app/pages/session/edit/index.vue
Don't allow text selection on small screens to give a more app-like feeling.
Also move up the hidden button for developer information and clean up a duplicate page validation.
> feat(app): disable text selection

- src/app/components/layout/menu/LayoutMenuBottomNavigation.vue
- src/app/composables/platform.ts
- src/server/middleware/platform.ts
- src/server/types/platform.d.ts
Offset needs to be bigger.
Also adds some logging to platform functionality.
> feat(components): double menu bottom padding for ios
