README.md, nuxt/nuxt.config.js, nuxt/package.json, nuxt/pages/account/_username/index.vue, nuxt/pages/event/_username/_event_name.vue, nuxt/pages/index.vue, nuxt/plugins/baseUrl.js
Add  basic open graph meta tags
This is a static approach for now, including i18n.
I've added both the description and og:description tag with different i18n paths. The description is subject for SEO, but not the og:description.
The url is not overridden.
=> feat(og-meta): add open graph meta tags to index page

nuxt/components/_/Menu.vue
Removes the class that hides the menu content. Since the menu itself is hidden based on the correct breakpoint repeating the hiding of the content is an unnecessary duplication. 
Fixes #816
=> fix: :bug: fix menu being empty in between tablet and phone breakpoint

nuxt/dev.sh
I run into an error getting started with development on alpjha, because set -e is an invalid sh option for me.
I'm not an expert, and it's difficult to me to google this for definite confirmation, but isn't `set -{}` only supported in more suffisticated shells?
Once i replaced the shebang with /bin/bash, it worked fine.
I'd suggest to change this for better interoperability.
=> fix(scripts): fix invalid shell in dev.sh

README.md
LGTM is closing end of this year.
They added a banner to their homepage and wrote more about it [here](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/). TLDR: team joined github, added features to githubs code analysis.
This also means that the LGTM badge won't work anymore starting in december.
I looked around, but i didn't find a proper replacement for the language quality badge yet. So, I added some other interesting badges to the readme. Hope it's in your interest.
=> docs(readme): replace lgtm badge with some github insight badges

nuxt/nuxt.config.ts, nuxt/server/api/auth.ts, nuxt/utils/auth.ts, nuxt/utils/constants.ts
Chrome would block cookies prefixed with `__Secure-` in non-https contexts.
Resolves #1010.
=> fix(auth): use secure cookie only in production

nuxt/app.vue, nuxt/pages/index.vue
Cookie reactivity configuration should of course not be on the root page only, but on all pages of the app.
=> fix(cookie-control): correct page placement

nuxt/components/button/event/ButtonEventNew.vue, nuxt/components/icon/IconContainer.vue, nuxt/server/middleware/headers.ts
See https://github.com/maevsi/maevsi/issues/1047
I've also pushed the following changes to this PR:
- remove non-existent `is-primary` property
- correct svg title placement
=> fix(csp): enable xss protection header

README.md
FOSSA now checks all licenses, e.g. of dependencies, for issues.
=> docs(readme): add a license scan badge

nuxt/package.json
`docker-entrypoint.sh` is not part of the Cypress image anymore. It should still be as far as I see, because of the Node base image being used, but it appears gone somehow. All of which doesn't really matter though as just resetting the entrypoint fulfills our initial goal, which was worked around with using `docker-entrypoint.sh` until now.
=> fix(cypress): correct entrypoint for v12.4

.vscode/settings.json
Does not seem to be required anymore, most likely due to better typescript interpretation by [Volar instead of Vetur](https://github.com/johnsoncodehk/volar/discussions/583).
=> chore(vscode): remove eslint configuration

.vscode/extensions.json
We don't use Apollo GraphQL anymore and their extension is not available on the [Open VSX Registry](https://open-vsx.org/), so we can replace it with the generally available GraphQL extension.
=> chore(vscode): use generally available graphql extension

.github/workflows/docker.yml
This action now uses official GitHub actions for Docker under the hood instead of a selfmade script: https://github.com/dargmuesli/github-actions/blob/d6b6c8baeeb9b3754d86d8eb94ff65b59e876a86/.github/workflows/docker3.yml
Also, the addition of build output zip files to GitHub releases is removed, because I don't see it being useful currently.
=> ci(docker): use v3

nuxt/nuxt.config.ts, nuxt/types/modules/vue.d.ts
Does not seem to be required anymore, most likely due to better typescript interpretation by [Volar instead of Vetur](https://github.com/johnsoncodehk/volar/discussions/583).
=> chore(types): remove vue shim

.github/workflows/release-schedule.yml
It's good practice to let cronjobs run at random times to not have all jobs being triggered at once. This PR sets the cronjob for automatic releases to run on Saturday instead of Monday.
=> ci(release-schedule): set random cron day

.vscode/settings.json
Reverts #1069 as accounted for by adding an explanation that prevents a future erroneous deletion.
GitHub displays jsonc comments in their file preview with a red background color, but the comment seems to not interfere with functionality in vscode.
=> chore(vscode): readd eslint configuration with added explanation

nuxt/.stylelintrc, nuxt/package.json, nuxt/pnpm-lock.yaml
[Prettier v15 decided to stop feeling responsible for general code styling and now let's prettier itself do that job](https://stylelint.io/migration-guide/to-15/#deprecated-stylistic-rules), thus dropping own prettier configuration.
=> chore(stylelint): remove prettier configuration

nuxt/app.vue, nuxt/cypress/e2e/event.cy.ts, nuxt/cypress/e2e/index.cy.ts, nuxt/cypress/e2e/legalnotice.cy.ts, nuxt/cypress/e2e/privacypolicy.cy.ts, nuxt/cypress/e2e/taskAccountPasswordResetRequest.cy.ts, nuxt/cypress/e2e/taskAccountRegister.cy.ts, nuxt/cypress/e2e/taskAccountSignIn.cy.ts, nuxt/cypress/e2e/taskEventUnlock.cy.ts, nuxt/cypress/e2e/taskSearch.cy.ts, nuxt/cypress/e2e/teapot.cy.ts, nuxt/nuxt.config.ts, nuxt/package.json, nuxt/plugins/gtag.client.ts, nuxt/pnpm-lock.yaml
I've [put some work into the cookie module](https://github.com/dargmuesli/nuxt-cookie-control/pull/42/files) so we can now add links e.g. to Privacy Policies of third party cookie providers. It's also a good idea to use (short) cookie ids to save bandwidth.
=> feat(cookie-control): set links and shorten ids

Dockerfile, docker/entrypoint-dev.sh, nuxt/package.json
Adds an entrypoint script that installs dependencies from the perspective of the cypress stage.
@PatrickMi The `sharp` error on development should not occur from the looks of it, as the dependencies are installed by that stage already. I'd need to take a second look at your installation.
=> fix(docker): install dependencies in cypress stage

CONTRIBUTING.md
As observed in https://github.com/maevsi/maevsi/pull/1122#discussion_r1148584077 it's a good idea to have a place where the common Single File Component format is defined.
Resolves #895
=> docs(contributing): explain script setup order

README.md, nuxt/package.json
All dargstack repositories now live under https://github.com/dargstack :partying_face:
=> docs(readme): migrate to new organization name

nuxt/package.json, nuxt/pnpm-lock.yaml
Stop following edge updates, use beta releases instead.
=> chore(deps): use @nuxtjs/i18n v8.0.0-beta.10

package.json
GitKraken now supports Git's `core.hooksPath` setting, so the custom prepare script is not needed anymore.
=> chore(package): simplify prepare script

nuxt/components/_/ImageUploadGallery.vue, nuxt/components/account/AccountProfilePicture.vue, nuxt/server/api/tusd.ts
Resolves #1140
Unsure why image loading stopped working.
We currently only save the `uploadId` and not the multipart `uploadId`. Both ids are separated by a plus sign. Adding a character after the plus sign, like another one, seems to fill in the multipart `uploadId`, preventing an error. Again, I don't know why leaving the second id out ever worked.
We now use both ids.
=> fix(tusd): workaround image url suffix

.dockerignore
Accounts for the new workspace structure, ignoring e.g. `node_modules` on multiple directory levels.
=> fix(docker): correct ignore file

nuxt/components/_/ImageUploadGallery.vue
Fix for the upload page. Previously: 
Now: 
The icon container is now square, which should be the case. It's the icon itself that does not have equal space around the x and y axis, but that's something for another ticket.
=> fix(image-upload-gallery): correct button trash margin

nuxt/components/icon/IconContainerNew.vue
`div`s might not be allowed under `button`s, for example.
How to review:
- check the nuxt console after a page reload: it should not show `error  <div> element is not permitted as content under <span>  element-permitted-content` for example on the upload page
- see if any icons break; they should not
=> fix(icon-container): use span for icons

nuxt/components/layout/LayoutMenu.vue
The button should have no icon, especially not the calendar icon. Seems to have been placed there by mistake.
=> fix(menu): remove calendar icon

nuxt/.codegenrc.ts
This way, one does not have to place that line into the generated file manually after each regeneration.
=> chore(codegen): automatically add eslint disable rule

sqitch/deploy/table_contact.sql, sqitch/deploy/table_event.sql, sqitch/deploy/table_event_group.sql, sqitch/deploy/table_event_grouping.sql, sqitch/deploy/table_invitation.sql, sqitch/deploy/table_notification.sql, sqitch/deploy/table_profile_picture.sql, sqitch/deploy/table_upload.sql
Having it before `ON DELETE CASCADE` results in a parsing error.
=> fix(sqitch): place not null constraint after type

.github/workflows/ci.yml
`8BitJonny/gh-get-current-pr` has a `pr_found` output that`s `true` if a PR has been found, which should be used instead of checking for string emptyness on the JSON output.
=> ci: correct pull request check

nuxt/composables/useDateTime.ts, nuxt/composables/useHost.ts, nuxt/pages/teapot/index.vue, nuxt/utils/auth.ts
`ssrContext` can pretty much always be accessed whereas `useRequestEvent` cannot.
=> refactor(nuxt): always use `ssrContext` to get request event

nuxt/components/form/FormContact.vue
Shows a user readable text instead of the English only database error message.
=> feat(contact): translate message for duplicate key violation

nuxt/app.vue
`$pwa` does not seem to be reactive, so a getter function needs to be used.
=> fix(app): correct pwa watcher

nuxt/server/api/tusd.ts
When an upload's binary data is removed, the storage key saved to maevsi's db does not resolve and leads to a 404. You can try that by creating an upload, then removing it in minio only. Obviously a 404 is not `ok`, so that `if` needs to be removed.
=> fix(upload): allow removal on invalid storage key

src/server/api/ical.post.ts, src/tests/unit/ical.test.ts
I renamed the api file so that it's not necessary to check the method being used internally.
=> refactor(ical): check api method via file name

src/server/tsconfig.json
After adding [server types](https://nuxt.com/docs/guide/directory-structure/server#server-types) some imports do not show correctly. This PR adds a workaround until better Nuxt generated types are available.
=> chore(server): customize types

src/components/card/Card.vue
When hiding all `Card` overflows, as currently done on `beta`, modals do not allow to scroll content. This PR allows scrolling in modals again.
=> fix(card): allow vertical overflow

src/components/form/Form.vue, src/components/form/account/password/FormAccountPasswordChange.vue
The  `Form` components needs to expose its reset method to be callable from a parent component.
=> fix(form): allow reset

.github/workflows/browserslist-regex.yml, .github/workflows/ci.yml, .github/workflows/release-schedule.yml, src/nuxt.config.ts
Read release name from environment variable so that the upcoming release is preferred in contrast to the still current commit.
=> fix(nuxt): read release name from environment variable

src/components/layout/LayoutBreadcrumbs.vue
Fix missing icon for separators in breadcrumbs.
=> fix(breadcrumbs): correct separator icon

src/nuxt.config.ts
The postcss configuration should not be needed anymore now that `@nuxtjs/tailwindcss` is in use.
=> chore(tailwind): remove postcss configuration

src/pages/session/create.vue
See https://github.com/maevsi/maevsi/issues/1510
Removes the error on the sign in page when already signed in.
=> feat(session): allow to create when already signed in

src/composables/gtag.ts, src/config/environments/development.ts
Currently, the consent does not seem to update on initial page load, which it should. Therefore all consent is denied in future page visits after giving consent. This PR changes the behavior of consent updates.
=> fix(gtag): update consent on initial page load

src/.config/nuxt.ts
TipTap's HTML is stored unescaped (is escaped when displayed) so api requests would trigger the xss protection on forward authentication.
Resolves https://github.com/maevsi/maevsi/issues/1603
=> fix(security): disable xss validator on internal authentication proxy

src/components/form/account/FormAccountRegistration.vue, src/components/form/account/FormAccountSignIn.vue, src/components/form/input/FormInputCaptcha.vue
The token is only valid once. If it is set directly after retrieving it, it'll be used for the first request following and unset directly afterwards. In case of the registration form that would be likely the username existence check and the token would not be valid for the form submission later on.
Now we set the token on form submission only.
=> fix(form): set captcha token on submit instead of on fetch

package.json, src/.config/nuxt.ts, src/server/plugins/event-stream.ts, src/server/utils/constants.ts, src/server/utils/email.ts, src/server/utils/notification.ts
Instead of hardcoding a magic number only, let the email's 24h sending limit be configurable through environment variables too. The magic number stays as a fallback.
=> feat(email): allow change to 24h limit through environment variable

.github/semantic.yml
As we're using squash merges now and only the PR title lands on the default branch as commit title, we can use the default semantic configuration again.
@huzaifaedhi22 if you merge master into your branches that are currently failing because of commit title formatting after this PR is merged (feel free to merge), they shouldn't be failing anymore.
=> chore(semantic): revert to default

src/package.json
The Nuxt server does not start with the current Sentry wrapper in production. There is no log indicating why. This disables the Sentry wrapper per default and keeps it as an alias for future debugging.
=> fix(sentry): disable server wrapper

src/config/environments/development.ts
Following a security fix in vite (https://github.com/advisories/GHSA-vg6x-rcgg-rjx6) we must now specify that `maevsi` is a valid host which comes into play in our stack deployment.
We also currently need to mark a few dependencies as not to be externalized by vite due to a regression in Nuxt (https://github.com/nuxt/nuxt/issues/30749).
=> fix(vite): allow host `maevsi`

src/config/environments/development.ts
The change that caused the regression in Nuxt v3.15.3 was reverted in v3.15.4: https://github.com/nuxt/nuxt/pull/30802
=> chore(vite): remove `noExternal` workaround

src/server/api/upload.delete.ts, src/server/middleware/timezone.ts, src/server/utils/auth.ts, src/server/utils/testing.ts, src/server/utils/timezone.ts
Convert come server utilities to the logic known from composables in the frontend (they're just called `utils` in the backend, eventhough they start with `use` afaik). Makes use of Nitro's `asyncContext` feature to get `event` information.
Also makes use of the `getRequestHeader` function instead of reading form `node.req.headers`.
=> refactor(server): extract "composables"

Dockerfile
Should fix the `ERR_PNPM_NO_OFFLINE_TARBALL` pipeline issue.
The pnpm version that was used to run `pnpm fetch` was not the one specified in the `package.json` as that file was not yet available at runtime. The next pnpm command had the project's pnpm version available though which resulted in a mismatch.
I'd like to keep `package.json` not being copied and specify the package manager version to use in a separate config file, but I think this is currently the only place where one can configure the package manager.
=> ci(docker): let pnpm fetch with correct version

src/server/api/notification.post.ts, src/server/utils/dependencies/firebase.ts, src/server/utils/dependencies/index.ts, src/server/utils/firebase.ts, src/server/utils/index.ts
Wraps the firebase admin initialization in a try-catch-statement so that an error while parsing the credentials does not make the whole server fail to start.
=> fix(firebase): try initialization

src/.config/nuxt.ts, src/config/environments/production.ts, src/sentry.server.config.ts
Sentry's tracing loads OpenTelemetry modules that internally use `require` which is not available in ESM.
This PR also disables Sentry in development.
cc @myyxl
=> fix(sentry): temporarily disable tracing

src/app/pages/session/edit/[id]/language.vue, src/sentry.server.config.ts, src/server/utils/notification.ts
Another try to fix the `require` issue in production.
=> fix(sentry): disable profiling

src/app/service-worker/sw.ts
In the service worker the received notification message will be transformed into a data message, bypassing Firebase's own handler, so we can show the notification once.  
cc @dargmuesli
If you want to test it, remember to set the worker-src CSP.
I tested it on iOS bookmark and Chrome
@dargmuesli do you know how to handle the types here? Feel free to push, so we don't need to disable eslint.
=> fix(sw): use data field for notification

.github/workflows/browserslist-regex.yml, .github/workflows/ci.yml, .github/workflows/release-schedule.yml
We now depend on `mkcert` but this wasn't added to all workflows yet.
cc @HMDank
=> ci(browserslist-regex): add dependency `mkcert`

Dockerfile
To specify compatible versions of other services, I introduce a "dependency" section at the top of the Dockerfile. These dependencies are not used by any stage below so they are not downloaded at build time. Renovate should notice breaking changes should allow for basic cross-language dependency management.
=> ci(docker): specify service dependencies

src/app/components/form/input/FormInput.vue
We can't expect placeholders to be set for all form inputs anymore.
=> chore(components): disable placeholder validation

src/app/pages/account/password/reset/index.vue, src/app/pages/account/verify/index.vue, src/app/pages/session/edit/[id]/index.vue, src/app/pages/🫖/index.vue, src/config/modules/index.ts, tests/e2e/specs/server/robots.spec.ts-snapshots/robots-txt-content-Mobile-Chrome-linux.txt, tests/e2e/specs/server/robots.spec.ts-snapshots/robots-txt-content-Mobile-Safari-linux.txt, tests/e2e/specs/server/robots.spec.ts-snapshots/robots-txt-content-chromium-linux.txt, tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-Mobile-Chrome-linux.xml, tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-Mobile-Safari-linux.xml, tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-de-chromium-linux.xml, tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-Mobile-Chrome-linux.xml, tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-Mobile-Safari-linux.xml, tests/e2e/specs/server/sitemap.spec.ts-snapshots/sitemap-content-en-chromium-linux.xml
Now that we use route rules, we can drop the hardcoded path excludes for `robots.txt` and sitemap.
Crawlers can access any page, but are instructed to ignore the ones disabled.
=> feat(pages): prefer route rules for robots configuration

src/app/components/app/radio/AppRadioGroup.vue, src/app/components/app/radio/AppRadioGroupItem.vue, src/app/components/form/FormEvent.vue, src/app/pages/session/edit/[id]/color-scheme.vue, src/app/pages/session/edit/[id]/language.vue
Refactors the current radio input to a non-form naming scheme and adds a new form variant of it.
=> refactor(components): integrate shadcn-nuxt's form into radio input

src/app/components/app/AppForm.vue, src/app/utils/api.ts, src/shared/utils/api.ts
The api utility's return value should not be modified externally.
=> chore(utils): make api computation readonly

src/app/components/event/report/EventReportDrawer.vue, src/app/composables/stepper.ts, src/app/pages/account/create/index.vue, src/app/pages/account/password/reset/index.vue, src/app/pages/account/password/reset/request.vue, src/app/pages/early-bird/create.vue
Instead of using a numbered index, a named stepper composable is extracted.
=> refactor(composables): extract named stepper

src/server/assets/emails/EmailAccountPasswordResetRequest.vue, src/server/utils/notification.ts
Password reset emails don't mention the username anymore which increases security.
cc @huzaifaedhi22 I took over this task as I was working on updating the email dependencies already.
=> fix(server): remove username from password reset emails

src/app/components/app/button/AppButton.vue, src/app/components/early-bird/EarlyBirdForm.vue, src/app/components/early-bird/EarlyBirdSubmission.vue, src/app/components/early-bird/EarlyBirdWelcome.vue, src/app/components/typography/TypographyBodyMedium.vue, src/app/components/typography/TypographyBodySmall.vue
No need to use `v-slot` and `v-bind` in some cases. Gave some flexibility in usage but that hasn't really been used for these components.
=> refactor(components): simplify typography

src/config/environments/development.ts
Nuxt content's websocket should use the same configuration as Vite's hot module reloading to work when run behind a reverse proxy like traefik.
See:
- https://github.com/maevsi/stack/pull/197
=> fix(content): allow websocket connections in stack deployment

package.json
A new dependency can have its build script ignored.
=> chore(package): ignore built dependency `@tailwindcss/oxide`

pnpm-lock.yaml, src/eslint.config.js, src/package.json
If we don't care about an error/warning we should disable it instead of having warning fly around the codebase. Also by adding this we notice once additional linter rules are turned on as what was fixed in https://github.com/maevsi/vibetype/pull/1936.
=> ci: let eslint error only

src/.codegenrc.ts
Saves us from having to revert the `type` removal in generated GraphQL files, the `useTypeImports` configuration is now available for all codegen plugins.
cc @huzaifaedhi22 @myyxl
=> chore(gql): generate type imports for all files

src/app/components/event/report/EventReportDrawer.vue, src/app/composables/stepper.ts, src/app/pages/account/create/index.vue, src/app/pages/account/password/reset/index.vue, src/app/pages/account/password/reset/request.vue, src/app/pages/early-bird/create.vue, src/app/pages/support/contact/index.vue
Improve stepper typing. It's not necessary to specify `default` anymore, it's included be default.
cc @huzaifaedhi22
=> refactor(composables): let stepper include `default` by default

src/shared/types/api.d.ts, src/shared/types/utility.d.ts
Improves typing while we wait for https://github.com/nitrojs/nitro/pull/3368 to be released.
=> fix(types): add workaround for upstream nitro issue

src/.config/nuxt.ts, src/config/modules/index.ts
Module configuration lives in a separate folder.
=> chore(nuxt): properly place shadcn module configuration

src/app/composables/alert.ts, src/app/composables/intl.ts, src/app/composables/networking.ts, src/app/composables/stepper.ts
Outside of components or pages, the global i18n scope needs to be used.
This PR added an error on duplicate local scope use: https://github.com/intlify/vue-i18n/pull/2204
The error page could also not be rendered due to i18n throwing an error, it appears: https://github.com/nuxt-modules/i18n/issues/3390
cc @huzaifaedhi22 this should fix the new issue that occurred in development only.
=> chore(composables): use global i18n

src/app/components/account/AccountBlockDrawer.vue, src/app/components/account/AccountDeleteDrawer.vue, src/app/components/event/report/EventReportDrawer.vue, src/app/pages/account/view/[username].vue, src/app/pages/event/view/[username]/[event_name]/index.vue
This PR
- allows users to block others directly from profile without having to reporting an event
- redirects to dashboard if user blocks an organizer after reporting an event
=> feat(account): block directly from profile

.github/workflows/browserslist-regex.yml, .github/workflows/ci.yml, .github/workflows/release-schedule.yml
It's good practice to set the minimal permissions needed for CI workflows.
=> ci(github): set workflow permissions explicitly

tests/e2e/specs/server/ical.spec.ts
Let's see if we can safely reenable this test.
=> test(e2e): reenable ical post test
